---
name: haskell-template-setup
version: 0.1.0.0
github: "fmidue/haskell-template-setup"
license: MIT
author: "Marcellus Siegburg"
maintainer: "marcellus.siegburg@uni-due.de"
copyright: "2020 Formal Methods in Computer Science - University of Duisburg-Essen"
extra-source-files:
  - README.md
  - ChangeLog.md
synopsis: A task type setup for haskell template tasks of the e-learning platform Autotool
category: E-Learning
description: Please see the README on GitHub at <https://github.com/marcellussiegburg/haskell-template-setup#readme>
dependencies:
  - base >= 4.7 && < 5
  - flex-tasks
  - logic-tasks
  - output-blocks
  - parsec
  - string-interpolate
  - syb
  - term-tasks
  - yesod-form
library:
  source-dirs: .
