---
name: Compile and Lint Flex-Tasks

on:
  push:
    branches: [main]
# t
permissions: write-all

jobs:
  test:
    uses: fmidue/flex-tasks/.github/workflows/test-flex.yml@workflow-reusable
    secrets: inherit
    with:
      tasks: tasks
      config: config
      settings-gens: test-gens
      script: tasks
      commit: ${{ github.sha }}
