---
name: Compile and Lint Flex-Tasks

#env:
#  TERM: xterm

on:
  push:
    branches: [main]

permissions: read-all

jobs:
  test:
    uses: fmidue/flex-tasks/.github/workflows/test-flex.yml@workflow-reusable
    permissions:
      contents: write
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    with:
      tasks: tasks
      config: config
      settings-gens: test-gens
      commit: ${{ github.sha }}
